repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  # Core AI/ML Services
  - name: whis-logic
    namespace: linkops
    chart: ./helm/whis_logic
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/whis_logic
          tag: latest
      - service:
          port: 8001
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  - name: whis-kubeflow
    namespace: linkops
    chart: ./helm/whis_kubeflow
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/whis_kubeflow
          tag: latest
      - service:
          port: 8005
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  - name: whis-data-input
    namespace: linkops
    chart: ./helm/whis_data_input
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/whis_data_input
          tag: latest
      - service:
          port: 8004
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  - name: whis-sanitize
    namespace: linkops
    chart: ./helm/whis_sanitize
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/whis_sanitize
          tag: latest
      - service:
          port: 8003
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  - name: whis-smithing
    namespace: linkops
    chart: ./helm/whis_smithing
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/whis_smithing
          tag: latest
      - service:
          port: 8005
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  - name: whis-enhance
    namespace: linkops
    chart: ./helm/whis_enhance
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/whis_enhance
          tag: latest
      - service:
          port: 8006
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  - name: whis-webscraper
    namespace: linkops
    chart: ./helm/whis_webscraper
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/whis_webscraper
          tag: latest
      - service:
          port: 8009
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  # Platform Engineering Services
  - name: igris-logic
    namespace: linkops
    chart: ./helm/igris_logic
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/igris_logic
          tag: latest
      - service:
          port: 8011
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
          AWS_ACCESS_KEY_ID: "dummy"
          AWS_SECRET_ACCESS_KEY: "dummy"
          AWS_DEFAULT_REGION: "us-east-1"

  - name: katie-logic
    namespace: linkops
    chart: ./helm/katie_logic
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/katie_logic
          tag: latest
      - service:
          port: 8012
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  # AI Assistant Services
  - name: james-logic
    namespace: linkops
    chart: ./helm/james_logic
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/james_logic
          tag: latest
      - service:
          port: 8002
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
          OPENAI_API_KEY: "sk-dummy"

  # Deployment & Evaluation Services
  - name: ficknury-deploy
    namespace: linkops
    chart: ./helm/ficknury_deploy
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/ficknury_deploy
          tag: latest
      - service:
          port: 8007
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  - name: ficknury-evaluator
    namespace: linkops
    chart: ./helm/ficknury_evaluator
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/ficknury_evaluator
          tag: latest
      - service:
          port: 8008
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  # Audit & Security Services
  - name: audit-logic
    namespace: linkops
    chart: ./helm/audit_logic
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/audit_logic
          tag: latest
      - service:
          port: 8014
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  - name: audit-assess
    namespace: linkops
    chart: ./helm/audit_assess
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/audit_assess
          tag: latest
      - service:
          port: 8015
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  - name: audit-migrate
    namespace: linkops
    chart: ./helm/audit_migrate
    values:
      - replicaCount: 1
      - image:
          repository: ghcr.io/shadow-link-industries/audit_migrate
          tag: latest
      - service:
          port: 8016
      - env:
          DATABASE_URL: "postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@db:5432/linkops"
          KAFKA_BOOTSTRAP_SERVERS: "kafka:29092" 