from kafka import KafkaConsumer
import requests
import json
import uuid

ORB_API = "http://localhost:8000/api/orbs"

def create_orb_from_log(log):
    task_id = log.get("task_id", str(uuid.uuid4()))
    result_text = log.get("result", "")

    orb_payload = {
        "name": f"Auto-Orb: {task_id}",
        "description": result_text[:480],
        "category": "AutoGenerated"
    }

    res = requests.post(ORB_API, json=orb_payload)
    print(f"[Whis] Orb created for task {task_id} | Status: {res.status_code}")

if __name__ == "__main__":
    consumer = KafkaConsumer(
        "logs",
        bootstrap_servers="localhost:9092",
        auto_offset_reset="earliest",
        enable_auto_commit=True,
        group_id="whis-agent",
        value_deserializer=lambda m: json.loads(m.decode("utf-8"))
    )

    print("[Whis] Listening for logs...")
    for msg in consumer:
        log = msg.value
        if log.get("agent") == "katie" and "screenshot" in log.get("action", ""):
            print(f"[Whis] Processing screenshot log: {log.get('task_id')}")
            create_orb_from_log(log) 