"""Add script_content to Rune model

Revision ID: ebc762fbfe4d
Revises: de5d633d1d83
Create Date: 2025-06-20 11:04:51.012441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc762fbfe4d'
down_revision: Union[str, Sequence[str], None] = 'de5d633d1d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runes', sa.Column('script_content', sa.Text(), nullable=True))
    op.alter_column('runes', 'script_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runes', 'script_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('runes', 'script_content')
    # ### end Alembic commands ###
