"""enhance_whis_queue_with_status

Revision ID: 504629267976
Revises: eadd463a54d3
Create Date: 2025-06-20 15:10:24.728410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "504629267976"
down_revision: Union[str, Sequence[str], None] = "eadd463a54d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whis_queue",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_whis_queue_status"), "whis_queue", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_whis_queue_task_id"), "whis_queue", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_whis_queue_task_id"), table_name="whis_queue")
    op.drop_index(op.f("ix_whis_queue_status"), table_name="whis_queue")
    op.drop_table("whis_queue")
    # ### end Alembic commands ###
