"""add_whis_queue_table

Revision ID: eadd463a54d3
Revises: eb28b7f6740d
Create Date: 2025-06-20 15:07:26.559405

"""

from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eadd463a54d3"
down_revision: Union[str, Sequence[str], None] = "eb28b7f6740d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
