"""Add feedback to runes

Revision ID: eb28b7f6740d
Revises: ebc762fbfe4d
Create Date: 2025-06-20 14:51:12.256037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb28b7f6740d"
down_revision: Union[str, Sequence[str], None] = "ebc762fbfe4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runes",
        sa.Column(
            "feedback_score",
            sa.Float(),
            nullable=True))
    op.add_column(
        "runes",
        sa.Column(
            "feedback_count",
            sa.Integer(),
            nullable=True))
    op.add_column(
        "runes",
        sa.Column(
            "last_feedback",
            sa.Text(),
            nullable=True))
    op.add_column(
        "runes",
        sa.Column(
            "is_flagged",
            sa.Boolean(),
            nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runes", "is_flagged")
    op.drop_column("runes", "last_feedback")
    op.drop_column("runes", "feedback_count")
    op.drop_column("runes", "feedback_score")
    # ### end Alembic commands ###
