"""add_task_id_to_runes

Revision ID: efe071886c3b
Revises: 504629267976
Create Date: 2025-06-20 18:53:46.087252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efe071886c3b"
down_revision: Union[str, Sequence[str], None] = "504629267976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runes", sa.Column("task_id", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_runes_task_id"), "runes", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_runes_task_id"), table_name="runes")
    op.drop_column("runes", "task_id")
    # ### end Alembic commands ###
